language: cpp

os: osx

# Travis' Xcode 6.4 image is the last (and only current) image to provide
# the macosx10.9 and macosx10.10 SDKs, which are supported by Qt 5.5.
osx_image: xcode6.4

compiler: clang

env:
  - MACOS_SDK=macosx10.9
  - MACOS_SDK=macosx10.10

before_install:
  - xcodebuild -showsdks

script:
  - ./build.sh

before_deploy:
  - ln -s QtNetwork-$MACOS_SDK build/qtbase/lib/QtNetwork.framework/QtNetwork
  - pwd
  - ls -l "./QtNetwork-$MACOS_SDK"
  - ls -l ./build/qtbase/lib/QtNetwork.framework/QtNetwork
  - ls -l ./build/qtbase/lib/QtNetwork.framework/Versions/5/QtNetwork
  - file "./QtNetwork-$MACOS_SDK"
  - file ./build/qtbase/lib/QtNetwork.framework/QtNetwork
  - file ./build/qtbase/lib/QtNetwork.framework/Versions/5/QtNetwork

deploy:
  provider: releases
  api_key: $RELEASES_API_KEY
  file: QtNetwork-$MACOS_SDK
  skip_cleanup: true
  on:
    tags: true
